# -*- coding: utf-8 -*-
"""HomePricePrediction_Pratham.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnggVNgfRMD8_k755xYuSAtLbZHd2v7e
"""

import pandas as pd
import numpy as np
from sklearn import linear_model

from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/'

df=pd.read_csv('gdrive/My Drive/homeprice.csv')

df

df.bedrooms.median()

df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

df

reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

reg.intercept_

reg.predict([[3000, 3, 40]])

112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

reg.predict([[2500, 4, 5]])